<?php

/**
 * Prepares a node to be added to elastic
 *
 * @param $node
 * @return array
 */
function _elastic_prepare_node($node) {

  if ( ! is_object($node)) {
    return;
  }

  $params = array(
    'index' => 'node',
    'type' => $node->type,
    'body' => array(),
  );

  // Add the simple properties
  $wanted = array(
    'vid', 
    'uid', 
    'title', 
    'log', 
    'status', 
    'comment', 
    'promote', 
    'sticky', 
    'nid', 
    'type', 
    'language', 
    'created', 
    'changed', 
    'revision_timestamp', 
    'revision_uid'
    );
  $exist = array_filter($wanted, function($property) use($node) {
    return property_exists($node, $property);
  });

  foreach ($exist as $field) {
    $params['body'][$field] = $node->{$field};
  }

  /* REFACTOR FROM HERE TO A SINGULAR FUNCTION */

  // Add the body field if exists
  $body_field = isset($node->body) ? field_get_items('node', $node, 'body') : false;
  if ($body_field) {
    $params['body']['body'] = $body_field;
  }

  // Add the stars field if exists
  $stars_field = isset($node->field_stars) ? field_get_items('node', $node, 'field_stars') : false;
  if ($stars_field) {
    // typecasting to make sure this is set as an integer
    $stars_field[0]['value'] = (int)$stars_field[0]['value'];

    $params['body']['stars'] = $stars_field;
  }

  // Add the price field if exists
  $price_field = isset($node->field_price) ? field_get_items('node', $node, 'field_price') : false;
  if ($price_field) {
    $params['body']['price'] = $price_field;
  }

  // Add the country field if exists
  $country_field = isset($node->field_country) ? field_get_items('node', $node, 'field_country') : false;
  if ($country_field) {
    $params['body']['country'] = $country_field;
  }

  // Add the board type field if exists
  $board_type_field = isset($node->field_board_type) ? field_get_items('node', $node, 'field_board_type') : false;
  if ($board_type_field) {
    $params['body']['board_type'] = $board_type_field;
  }

  // Add the duration field if exists
  $duration_field = isset($node->field_duration) ? field_get_items('node', $node, 'field_duration') : false;
  if ($duration_field) {
    $params['body']['duration'] = $duration_field;
  }

  // Add the region field if exists
  $region_field = isset($node->field_region) ? field_get_items('node', $node, 'field_region') : false;
  if ($region_field) {
    $params['body']['region'] = $region_field;
  }

  // Add the accommodation field if exists
  $accommodation_field = isset($node->field_accommodation) ? field_get_items('node', $node, 'field_accommodation') : false;
  if ($accommodation_field) {
    $params['body']['accommodation'] = $accommodation_field;
  }

  // Add the transportation field if exists
  $transportation_field = isset($node->field_transportation) ? field_get_items('node', $node, 'field_transportation') : false;
  if ($transportation_field) {
    $params['body']['transportation'] = $transportation_field;
  }

  // Add the city field if exists
  $city_field = isset($node->field_city) ? field_get_items('node', $node, 'field_city') : false;
  if ($city_field) {
    $params['body']['city'] = $city_field;
  }

  /* END OPTIONAL REFACTOR TO A SINGLE FUNCTION */

  // Add the image field if exists
  $image_field = isset($node->field_image) ? field_get_items('node', $node, 'field_image') : false;
  if ($image_field) {
    $params['body']['field_image'] = array_map(function($img) {
      $img = file_load($img['fid']);
      $img->url = file_create_url($img->uri);
      return $img;
    }, $image_field);
  }

  return $params;
}

/**
 * Helper function that returns a node from Elastic by its nid.
 *
 * @param $client
 * @param $node
 * @return mixed
 */
function _elastic_perform_node_search_by_id($client, $node) {
  $search = array(
    'index' => 'node',
    'type' => $node->type,
    'version' => true,
    'body' => array(
      'query' => array(
        'match' => array(
          'nid' => $node->nid,
        ),
      ),
    ),
  );

  return $client->search($search);
}

/**
 * Implements hook_node_insert().
 */
function elastic_node_insert($node) {
  $client = elasticsearch_connector_get_client_by_id('elasticsearch');
  $params = _elastic_prepare_node($node);

  if (empty($params['body']['field_image'])) {
    drupal_set_message(t('Skipped this insert because there is no image found for it'));
    return;
  }

  if ( ! $params) {
    drupal_set_message(t('There was a problem saving this node to Elastic.'));
    return;
  }

  // This actually inserts the node into elasticsearch, utisiling the $client->index() method from the elasticsearch php client
  $result = $client->index($params);

  if ($result && $result['created'] === false) {
    drupal_set_message(t('There was a problem saving this node to Elastic.'));
    return;
  }

  drupal_set_message(t('The node has been saved to Elastic.'));
}

/**
 * Implements hook_node_update().
 */
function elastic_node_update($node) {
  if ($node->is_new !== false) {
    return;
  }

  $client = elasticsearch_connector_get_client_by_id('elasticsearch');
  $params = _elastic_prepare_node($node);

  if ( ! $params) {
    drupal_set_message(t('There was a problem updating this node in Elastic.'));
    return;
  }

  $result = _elastic_perform_node_search_by_id($client, $node);
  if ($result && $result['hits']['total'] !== 1) {
    drupal_set_message(t('There was a problem updating this node in Elastic.'));
    return;
  }

  $params['id'] = $result['hits']['hits'][0]['_id'];
  $version = $result['hits']['hits'][0]['_version'];
  $index = $client->index($params);

  if ($index['_version'] !== $version + 1) {
    drupal_set_message(t('There was a problem updating this node in Elastic.'));
    return;
  }
  
  drupal_set_message(t('The node has been updated in Elastic.'));
}

/**
 * Implements hook_node_delete().
 */
function elastic_node_delete($node) {
  $client = elasticsearch_connector_get_client_by_id('elasticsearch');

  // If the node is in Elastic, remove it
  $result = _elastic_perform_node_search_by_id($client, $node);
  if ($result && $result['hits']['total'] !== 1) {
    drupal_set_message(t('There was a problem deleting this node in Elastic.'));
    return;
  }

  $params = array(
    'index' => 'node',
    'type' => $node->type,
    'id' => $result['hits']['hits'][0]['_id'],
  );

  $result = $client->delete($params);
  if ($result && $result['found'] !== true) {
    drupal_set_message(t('There was a problem deleting this node in Elastic.'));
    return;
  }

  drupal_set_message(t('The node has been deleted in Elastic.'));
}